name: Continuous Integration
on:
  pull_request:
    branches:
      - main

jobs:
  buil:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Python Lint Code Scanning Action
        uses: advanced-security/python-lint-code-scanning-action@v1.1.1
        with:
          linter: pylint

  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        # Add support for more platforms with QEMU (optional)
        # https://github.com/docker/setup-qemu-action
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build
        uses: docker/build-push-action@v6
        with:
          context: .
          push: false
          tags: user/app:latest


  discord:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2

    name: Send a message to Microsoft Teams
    uses: aliencube/microsoft-teams-actions@v0.8.0
    with:
      webhook_uri: https://outlook.office.com/webhook/<GUID>/IncomingWebhook/<GUID>
      title: <Message Title>
      summary: <Message Summary>
      text: <Message Text>
      theme_color: <Message Theme Color>
      sections: '[{ "activityTitle": "hello world" }, { ... }]'
      actions: '[{ "@type": "OpenUri", "name": "lorem ipsum", "targets": [{ "os": "default", "uri": "https://localhost" }] }, { ... }]'
  For more details about sections and actions:
